spring.application.name=gerenciador-armazenamento
server.port=3000
spring.datasource.url=jdbc:mysql://localhost:3306/dbgerenciador
spring.datasource.username=${USER_DB}
spring.datasource.password=${SENHA_DB}